### ISSUE TITLE
Not in NPM Registry 

### ISSUE THREAD

**Issue by aspatti** [jjdltc/jjdltc-cordova-plugin-zip#13]
Cordova serve display the following error:
Discovered plugin "com.jjdltc.cordova.plugin.zip". Adding it to the project
Failed to restore plugin "com.jjdltc.cordova.plugin.zip". You might need to try adding it again. Error: Error: Command failed with exit code 1: npm view com.jjdltc.cordova.plugin.zip --json
npm ERR! code E404
npm ERR! 404 'com.jjdltc.cordova.plugin.zip' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 404
npm ERR! 404  'com.jjdltc.cordova.plugin.zip@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-11T16_48_29_259Z-debug.log
{
  "error": {
    "code": "E404",
    "summary": "'com.jjdltc.cordova.plugin.zip' is not in the npm registry.\nYou should bug the author to publish it\n(or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url.",
    "detail": "\n 'com.jjdltc.cordova.plugin.zip@latest' is not in the npm registry.\nYou should bug the author to publish it (or use the name yourself!)\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}

**Comment by jjdltc** [comment]
Hi there, 

Did you try this => `cordova plugin add cordova-zip-plugin` as mention in [here](https://github.com/jjdltc/jjdltc-cordova-plugin-zip#installation)

As reference the npm package is => https://www.npmjs.com/package/cordova-zip-plugin

Hope this solve your issue and allow to use the package :)

**Comment by aspatti** [comment]
Hi 
I installed the plugin using:
cordova plugin add cordova-zip-plugin
and 
cordova plugin ls
displays
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"

but when I run
cordova serve
it displays the above mentioned error.

**Comment by jjdltc** [comment]
Oh,

As I remember there is not yet a Browser implementation (I get one P.R. for that but didn't review it yet) so, by now you should wrap somehow the feature while you're on the browser to avoid it's use (It's only implemented for iOS and Android)

**Comment by jjdltc** [comment]
Just to be clear, the app should run (Even with `cordova serve`) the only problem will happen if you try to use the plugin on the browser, if you didn't call the plugin while in browser, then the rest of the app should work as usual.

**Comment by aspatti** [comment]
Yes the app is otherwise working.
I just removed the package manually from package.json and from the folder and reinstalled. Now the cordova serve/build working without previous error. 

I will check on Android soon and will update you. 
Thanks for your support

**Comment by aspatti** [comment]
Hi,
Plugin is working on Android.

After doing unzip, I want to call another method using this.methodname() and received following error:

error in Success callbackId: JJzip1142024672 : TypeError: Cannot read property 'method_name' of null

Some how callback method of unzip is hiding the current ojbect's method, any advise?
Thank you,

**Comment by aspatti** [comment]
Thanks, Everything is working as expected.
