### ISSUE TITLE
Still maintained ?

### ISSUE THREAD

**Issue by maudvd** [jjdltc/jjdltc-cordova-plugin-zip#18]
I was just wondering whether this plugin was still maintained or not. 
The old [cordova-plugin-zip](https://github.com/MobileChromeApps/cordova-plugin-zip) is not maintained so I was hoping on using this plugin as a replacement.

**Comment by jjdltc** [comment]
Hello @modvd Still maintained, but a slow rate.
Had a few PR pendings, fell free to check if any of those solve your issue and if so I might try to prioritize.
Keep in mind this was an old implementation for a need I had few years ago, it has being maintain base on that, but not necessarily evolved.

**Comment by maudvd** [comment]
No issues on my part, I was juste wondering because I try to avoid using unmaintained plugins. I use the plugin in my Ionic project and it works perfectly. Thank you very much for this plugin !
