### ISSUE TITLE
VS doesn't load the plugin

### ISSUE THREAD

**Issue by Elvoniel** [jjdltc/jjdltc-cordova-plugin-zip#2]
I have an issue on Visual Studio 2015, when i try to install the plugin VS tells me something like : "Visual Studio couldn't parse plugin.xml".

For the moment, i don't see what could be wrong, any idea ?

Thanks !

**Comment by Elvoniel** [comment]
Ok i juste resolve my issue. To make plugin.xml readable by VS you have to erease comments at the begening of the file. The first line of the file should be "<?xml version="1.0" encoding="UTF-8"?>".

**Comment by jjdltc** [comment]
Thanks for reporting that, I will check and update soon
