### ISSUE TITLE
Add password

### ISSUE THREAD

**Issue by distrilog** [jjdltc/jjdltc-cordova-plugin-zip#4]
Hi,

Can you add password fonctionnality to compress/decompress file ?

Best regards,
Nicolas

**Comment by jjdltc** [comment]
Hi Nicolas.

I believe that there is not a chance in actual `java.util.zip.*` to do such things, I also believe that with enough time I will (or someone or we) be able to extend the standard of zip files (With password) over the plugin (But thats not me right now).

So I will label this as "enhancement" and "help wanted", and added to pending (TODO), so if I can make I will (but not right now) or if someone make a request with the right changes also will be ok.

Regards
jjdltc.

**Comment by distrilog** [comment]
Thanks :)
