### ISSUE TITLE
'Bad zip' issue

### ISSUE THREAD

**Issue by eternalsayed** [jjdltc/jjdltc-cordova-plugin-zip#6]
The zip created using this plugin is about 24Kb in size and reports as 'bad zip' when I try to open it with some app. Can you please help?

**Comment by jjdltc** [comment]
could you please be more specific, giving:
- Android Version
- Device Model
- File type (And example of possible)
- Example (Code) of how you implement the plugin

And anything else that cuold help to understand the problem you face

**Comment by eternalsayed** [comment]
Never mind. I created my own zipping plugin.
