### ISSUE TITLE
its created two folder

### ISSUE THREAD

**Issue by sabirali007** [jjdltc/jjdltc-cordova-plugin-zip#7]
when i unzip a folder after zip, its create that folder inside with the same name.
for example if i zip vin folder after zipping when i unzip i found vin folder inside  vin folder
something like that
vin/vin
i want to zip just folder files not whole folder.
Thanks

**Comment by jjdltc** [comment]
Since recent update (Jan 2019) I can't reproduce this.
I'm sorry for the delay, i'm closing the issue as inactive (Blame me :/)
If still occurs, re-open a new one and I will look in the problem
